Отобразить фотографии других пользователей
htmlacademy-javascript/977171-kekstagram-21 pull request #2
Opened 2020-10-18 13:20 UTC by RuDovbnySe

2020-10-19 06:55 UTC, frontstall requested changes

2020-10-19 06:55 UTC, frontstall commented on js/main.js
> +const getRandomAvatar = (min, max) => {
min, кажется, можно опустить, а max не просто max, а maxId, например.

2020-10-19 06:55 UTC, frontstall commented on js/main.js
> +  const randomFotoId = Math.floor(Math.random() * (max - min + 1) + min);
есть же функция getRandomNumber, которая позволяет найти случайное число в интервале.

2020-10-19 06:55 UTC, frontstall commented on js/main.js
> +  const element = `img/avatar-${randomFotoId}.svg`;
это не элемент, это путь к файлу аватарки.

2020-10-19 06:55 UTC, frontstall commented on js/main.js
> +for (let i = 0; i < 25; i++) {
Нужна функция создания одного коммента:

```
const commentData = getCommentData(// * аргументы *//);
```

2020-10-19 06:55 UTC, frontstall commented on js/main.js
> +let picture = [];
Коллекции называем во множественном числе.

2020-10-19 06:55 UTC, frontstall commented on js/main.js
> +for (let i = 0; i < 25; i++) {
магическое число, и дальше в теле цикла тоже.

нужна функция генерации данных для одной картинки.

2020-10-19 06:55 UTC, frontstall commented on js/main.js
> +  const generatePictureData =
Попробуй оставлять фигурную скобку на той же строке, что и присваивание:

```
const object = {
  foo: 'bar',
  baz: 42,
};
```

2020-10-19 06:55 UTC, frontstall commented on js/main.js
> +  pictureElement.querySelector(`.picture__comments`).textContent = picture[i].comment;
Кажется, тут должны быть комменты, а не просто их число.

2020-10-24 12:19 UTC, RuDovbnySe commented on js/main.js
> +  pictureElement.querySelector(`.picture__comments`).textContent = picture[i].comment;
Как я понял, комментарии появляются, когда картинку "открываешь" и под ней комментарии. А тут пока только их количество.

2020-10-24 12:19 UTC, RuDovbnySe commented on js/main.js
> +  const generatePictureData =
done

2020-10-24 12:19 UTC, RuDovbnySe commented on js/main.js
> +let picture = [];
done

2020-10-24 12:19 UTC, RuDovbnySe commented on js/main.js
> +  const element = `img/avatar-${randomFotoId}.svg`;
done

2020-10-24 12:20 UTC, RuDovbnySe commented on js/main.js
> +  const randomFotoId = Math.floor(Math.random() * (max - min + 1) + min);
done

2020-10-24 12:20 UTC, RuDovbnySe commented on js/main.js
> +const getRandomAvatar = (min, max) => {
done

2020-10-24 13:59 UTC, RuDovbnySe commented on js/main.js
> +for (let i = 0; i < 25; i++) {
done

2020-10-24 14:00 UTC, RuDovbnySe commented on js/main.js
> +for (let i = 0; i < 25; i++) {
done

2020-10-27 07:39 UTC, frontstall requested changes

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +// const getUserPictures = document.querySelector('.picture');
Неиспользуемый код нужно удалять, есть критерий про мусор.

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +const getUserPictures = document.querySelector(`#picture`)
Это не функция, почему get? Ну и кажется можно проще:
```
document.querySelector(`#picture .picture`)
```

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +  const randomFotoId = getRandomNumber(1, 7);
магическое число

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +const commentOne = () => {
Название функции начинается с глагола

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +  const generateOneComment = {
А название объекта - не с глагола :)

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +const pictureOne = (i) => {
1) Именование функции
2) что такое `i`?

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +  const descriptions = getRandomArrayItem(DESCRIPTIONS);
Это не массив, поэтому в единственном числе

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +  const like = getRandomNumber(15, 200);
1) `like` - это лайк, а тут количество лайков, насколько я понимаю
2) магические числа

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +  const numberComment = getRandomNumber(1, 10);
1) commentsCount - число комментов
2) магическое число 10

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +  const generateOnePictures = {
Это не функция

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +let commentArray = [];
И так понятно, что это array. Просто `comments`

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +for (let i = 0; i < 25; i++) {
что такое 25?

2020-10-27 07:39 UTC, frontstall commented on js/main.js
> +  pool.appendChild(pictureElement);
Что такое `pool`? Это вроде переводится как бассейн)

2020-11-06 08:44 UTC, merged